// void never

const addNumbers=()=>{
    console.log(2+4)
}


addNumbers();



const throwNewError=()=>{
     throw new Error("your program is terminate")
}











